# See https://github.com/dart-lang/mono_repo for details
dart:
- dev

stages:
- analyze:
  - command: "dartanalyzer --fatal-warnings ."
  - command: "dartfmt --dry-run --set-exit-if-changed ."
- build:
  - command: "pub run build_runner build"
- unit_test:
  - command: "pub run build_runner test"
  - command: "pub run build_runner test -- -p chrome"

cache:
  directories:
  - .dart_tool/build