name: example

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/petitparser/dart-petitparser
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  petitparser:
    path: ../petitparser
dev_dependencies:
  test: ^1.3.0
