name: example

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/petitparser/dart-petitparser
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  collection: ^1.14.0
  more: ^1.17.0
  petitparser:
    path: ../petitparser
dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
