name: petitparser
version: 1.8.0
author: Lukas Renggli <renggli@gmail.com>
description: A dynamic parser framework to build efficient gramamars and
  parsers quickly.
homepage: https://github.com/petitparser/dart-petitparser
environment:
  sdk: ">=2.0.0-dev.69.4 <3.0.0"
dependencies:
  matcher: ^0.12.3
dev_dependencies:
  test: ^1.3.0
