name: petit_lisp
version: 6.4.0

homepage: https://github.com/amake/petit_lisp
repository: https://github.com/amake/petit_lisp.git
description: A simple Lisp implementation
topics:
  - lisp

environment:
  sdk: ^3.0.0
dependencies:
  petitparser: ^7.0.1
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^6.0.0
  test: ^1.24.0
  web: ^1.1.0
