name: petitparser
version: 0.2.1
description: Dynamic parser combinator framework.
author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/PetitParserDart
dependencies:
  unittest: any