name: petitparser
version: 0.2.5+m4
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
dev_dependencies:
  junitconfiguration: '>=0.4.7'
  unittest: '>=0.4.7'
  browser: '>=0.4.7'
