name: petitparser_examples
version: 6.0.1

homepage: https://petitparser.github.io
repository: https://github.com/petitparser/dart-petitparser-examples
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.
topics:
  - grammar
  - parser
  - parser-combinator
  - parsing
  - peg

environment:
  sdk: ^3.0.0
dependencies:
  collection: ^1.18.0
  data: ^0.12.0
  http: ^1.1.0
  meta: ^1.9.0
  more: ^4.0.0
  petitparser: ^6.0.0
  xml: ^6.4.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0
