name: petitparser
version: 0.5.4
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
dev_dependencies:
  browser: '>=0.7.0'
  junitconfiguration: any
  meta: '>=0.7.0'
  unittest: '>=0.7.0'
