name: petitparser_examples
version: 5.4.0

homepage: https://petitparser.github.io
repository: https://github.com/petitparser/dart-petitparser-examples
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

publish_to: none
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  collection: ^1.17.0
  http: ^0.13.0
  meta: ^1.9.0
  more: ^3.10.0
  petitparser: ^5.4.0
  xml: ^6.3.0
dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
  test: ^1.24.0

dependency_overrides:
  xml:
    git:
      url: https://github.com/renggli/dart-xml.git
      ref: main
  petitparser:
    git:
      url: https://github.com/petitparser/dart-petitparser.git
      ref: main