name: petitparser
version: 1.5.3
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/dart-petitparser
environment:
  sdk: ^1.8.0
dev_dependencies:
  browser: ^0.10.0
  matcher: ^0.12.0
  test: ^0.12.0
