name: petitparser
version: 0.2.3+m3
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
dependencies:
  unittest: '>=0.3.1+1'
  browser: '>=0.3.1+1'
