name: petitparser_examples
version: 5.2.0

homepage: https://petitparser.github.io
repository: https://github.com/petitparser/dart-petitparser-examples
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  collection: ^1.17.0
  http: ^0.13.0
  meta: ^1.9.0
  more: ^3.9.5
  petitparser: ^5.1.0
  xml:
    git: https://github.com/renggli/dart-xml.git
dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
  test: ^1.23.0
