name: petitparser
version: 0.5.7
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
dev_dependencies:
  browser: '>=0.8.0'
  junitconfiguration: any
  unittest: '>=0.8.0'
