name: petitparser
version: 1.3.5
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/dart-petitparser
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://jenkins.lukas-renggli.ch/job/dart-petitparser/javadoc
dev_dependencies:
  browser: '>=0.10.0 <0.12.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  matcher: '>=0.10.0 <0.12.0'
  unittest: '>=0.10.0 <0.12.0'
