name: petitparser
author: Lukas Renggli <renggli@gmail.com>
version: 1.1.0
homepage: https://github.com/renggli/PetitParserDart
description: Dynamic parser combinator framework.
documentation: http://jenkins.lukas-renggli.ch/view/Dart/job/PetitParserDart/javadoc
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  unittest: '>=0.9.0 <0.11.0'
