name: petitparser_examples
version: 4.5.0

homepage: https://github.com/petitparser/dart-petitparser
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  more: ^3.3.0
  petitparser:
    git: https://github.com/petitparser/dart-petitparser.git
dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  lints: ^1.0.0
  test: ^1.19.0
