name: petitparser
version: 0.4.0
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/PetitParserDart
dev_dependencies:
  junitconfiguration: '>=0.5.0'
  unittest: '>=0.5.0'
  browser: '>=0.5.0'
  meta: '>=0.5.0'
