name: petitparser_examples
version: 6.0.0

homepage: https://petitparser.github.io
repository: https://github.com/petitparser/dart-petitparser-examples
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: ^3.0.0
dependencies:
  collection: ^1.17.0
  http: ^1.0.0
  meta: ^1.9.0
  more: ^4.0.0
  petitparser: ^6.0.0
  xml: ^6.3.0
dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
  test: ^1.24.0

dependency_overrides:
  petitparser:
    git: https://github.com/petitparser/dart-petitparser.git
  xml:
    git: https://github.com/renggli/dart-xml.git