name: petitparser
version: 1.7.7
author: Lukas Renggli <renggli@gmail.com>
description: A dynamic parser framework to build efficient gramamars and
  parsers quickly.
homepage: https://github.com/petitparser/dart-petitparser
environment:
  sdk: ">=1.20.0 <3.0.0"
dependencies:
  matcher: ^0.12.0
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
