name: petitparser
version: 1.4.0
author: Lukas Renggli <renggli@gmail.com>
description: Dynamic parser combinator framework.
homepage: https://github.com/renggli/dart-petitparser
documentation: http://jenkins.lukas-renggli.ch/job/dart-petitparser/javadoc
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.1 <0.13.0'
