name: Dart CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Dart CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: "Dependencies"
        run: dart pub upgrade --no-precompile
      - name: "Dart Analyzer"
        run: dart analyze --fatal-infos .
      - name: "Dart Formatter"
        run: dart format --output=none --set-exit-if-changed .
      - name: "VM Tests"
        run: dart test --platform vm test/lisp_test.dart
      - name: "Chrome Tests"
        run: dart test --platform chrome test/lisp_test.dart
      - name: "Collect coverage"
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage --test test/lisp_test.dart
      - name: "Upload coverage"
        uses: codecov/codecov-action@v5
  check:
    name: "Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amake/dart-flutter-compat@v0-pre2
        with:
          channel: stable
          cache: true
