name: Dart Deploy
defaults:
  run:
    shell: bash
    working-directory: ./petitparser_examples
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - uses: actions/checkout@v2
      - run: "dart pub global activate webdev"
      - run: "webdev build --release"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build